on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # to have access to the source code
      - uses: ./.github/actions/hello # referencing the custom action
        id: hello
        with:
          who-to-greet: "World"
      - run: |
          echo "Time: ${{steps.hello.outputs.time}}"
